name: orre
description: "Smart Consumer Life with OrRe"
publish_to: 'none'
version: 1.0.16+16

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  animated_flip_counter: ^0.3.4
  another_flutter_splash_screen: ^1.2.0
  app_links: ^6.1.1
  auto_animated: ^3.2.0
  awesome_dialog: ^3.2.1
  awesome_snackbar_content: ^0.1.3
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.8
  device_info_plus: ^10.1.0
  equatable: ^2.0.5
  firebase_analytics: ^10.10.5
  firebase_core: ^2.25.5
  firebase_messaging: ^14.7.17
  floating_action_bubble: ^1.1.4
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^14.0.0+1
  flutter_naver_map: ^1.1.2
  flutter_phone_direct_caller: ^2.1.1
  flutter_riverpod: ^2.4.10
  flutter_screenutil: ^5.9.1
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  flutter_test:
    sdk: flutter
  geocoding: ^2.2.0
  geolocator: ^11.0.0
  get: ^4.6.6
  go_router: ^14.1.3
  google_maps_flutter: ^2.5.3
  http: ^1.2.0
  internet_connectivity_checker: ^1.0.2
  # live_activities: ^1.9.1+1
  loader_overlay: ^4.0.0
  mockito: ^5.4.4
  nfc_manager: ^3.4.0
  package_info_plus: ^8.0.0
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  qr_code_scanner: ^1.0.1
  riverpod_annotation: ^2.3.4
  shared_preferences: ^2.2.3
  sliver_app_bar_builder: ^1.1.0
  sqflite: ^2.3.3
  stomp_dart_client: ^1.0.3
  stylish_bottom_bar: ^1.1.0
  url_launcher: ^6.3.0
  url_strategy: ^0.2.0



dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  flutter_oss_licenses: ^3.0.2
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true
  assets: 
    - .env
    - assets/images/orre_logo.png
    - assets/images/loading_orre.gif
    - assets/images/error_orre.gif
    - assets/images/waveform/wave_shadow.png
    - assets/images/waveform/wave.png
    - assets/images/waveform/orre_wave.svg
    - assets/images/waveform/orre_wave_shadow.svg

  fonts :
    - family: Dovemayo_gothic
      fonts :
        - asset : assets/fonts/Dovemayo_gothic.ttf
    - family: AppleSDGothicNeo
      fonts :
        - asset : assets/fonts/AppleSDGothicNeoR.ttf
    - family: NotoSansKR
      fonts :
        - asset : assets/fonts/NotoSansKR-Regular.ttf
        - asset : assets/fonts/NotoSansKR-Medium.ttf